### ISSUE TITLE
关于DRIM实验中的参考图像

### ISSUE THREAD

**Issue by ZealerMUFC** [baidut/BIMEF#1]
您好，请问在做DRIM实验时，您找的参考图片是怎么得来的？我也在做类似实验，所以想知道你是怎么获得这些参考图片。如果方便的话，请问能发给我几张吗？期待你的回答。

**Comment by baidut** [comment]
@ZealerMUFC  DRIM 的参考图像是曝光正常的图像。所以可以拿多曝光数据集进行测试。
