### ISSUE TITLE
您好，请问一下有关VIF的问题

### ISSUE THREAD

**Issue by yifanjiang19** [baidut/BIMEF#3]
您好，我们打算在paper中与BIMEF方法进行对比，但是这个repo中提供的VIF一直无法运行，请问您能给出一些建议吗？
这是运行vif.m时报错的内容：
MEX-file './BIMEF/quality/matlabPyrTools/corrDn.mexmaci64' 无效:
dlopen(./BIMEF/quality/matlabPyrTools/corrDn.mexmaci64, 6): Library not loaded: @loader_path/libmex.dylib
  Referenced from: ./BIMEF/quality/matlabPyrTools/corrDn.mexmaci64
  Reason: image not found。

**Comment by baidut** [comment]
看报错内容应该是matlabPyrTools没装好。你可以参考下这个 https://www.mathworks.com/matlabcentral/answers/369713-can-anyone-help-me-resolve-setting-a-path-to-dynamic-library-in-an-invalid-mex-file-runtime-error
实在不行，可以换个windows或者linux的机器安装、运行

**Comment by yifanjiang19** [comment]
好的谢谢，我把matlab版本换了之后可以用了，但是感觉VIF值和人眼看上去的效果并不是很相关，请问您有什么建议吗？

**Comment by baidut** [comment]
您好，建议组织进行human study. 对比不同方法处理结果的MOS比较有说服力，关键字：Paired-Comparison。可以参考这篇文章里面的主观实验部分。LECARM: Low-Light Image Enhancement using Camera Response Model

**Comment by yifanjiang19** [comment]
非常感谢，我看到您在上面提到的这篇paper的ICCV‘17 版本里用到了LOE和color distortion metric，这两个metric是否有效呢？

**Comment by baidut** [comment]
这些指标的结果可以参考，但不是很可靠

**Comment by yifanjiang19** [comment]
谢谢
